'use client';
import {useState} from 'react'; import {motion,useReducedMotion} from 'motion/react'; import {predictDisease,generateDiseaseReport} from '../../../lib/api';
type V={Age:number|'';Gender:string;TB:number|'';DB:number|'';Alkphos:number|'';Sgpt:number|'';Sgot:number|'';TP:number|'';ALB:number|'';'A/G Ratio':number|null|''};
const init:V={Age:'',Gender:'',TB:'',DB:'',Alkphos:'',Sgpt:'',Sgot:'',TP:'',ALB:'','A/G Ratio':''}; const groups=[['Patient information',['Age','Gender']],['Bilirubin measurements',['TB','DB']],['Liver enzymes',['Alkphos','Sgpt','Sgot']],['Protein measurements',['TP','ALB','A/G Ratio']]] as const; const labels:any={Age:'Age',Gender:'Gender',TB:'Total bilirubin',DB:'Direct bilirubin',Alkphos:'Alkaline phosphatase',Sgpt:'Alanine aminotransferase',Sgot:'Aspartate aminotransferase',TP:'Total proteins',ALB:'Albumin','A/G Ratio':'Albumin and globulin ratio'};
export default function LiverAssessment(){const [v,setV]=useState<V>(init);const[step,setStep]=useState(0);const[stage,setStage]=useState('intro');const[ack,setAck]=useState(false);const[result,setResult]=useState<any>();const[error,setError]=useState('');const reduced=useReducedMotion();const set=(k:string,x:any)=>setV({...v,[k]:x}); const valid=()=>{for(const k of groups[step][1]){const x=v[k as keyof V];if(x===''||x===undefined)return `${labels[k]} is required.`;if(typeof x==='number'&&x<0)return `${labels[k]} cannot be negative.`}return ''};const payload=()=>Object.fromEntries(Object.entries(v).map(([k,x])=>[k,x===''?null:x]));
async function submit(){setStage('processing');try{const r=await predictDisease('liver',payload());setResult(r);setStage('results')}catch{setError('We could not run this assessment. Check the API.');setStage('review')}} async function pdf(){const r=await generateDiseaseReport('liver',payload());if(r.ok){const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='liver-assessment-report.pdf';a.click()}}
if(stage==='intro')return <main className="page"><p className="eyebrow">LIVER ASSESSMENT</p><h1>Explore a liver disease risk pattern</h1><div className="card"><p>This educational module uses the Indian Liver Patient Dataset and a persisted Random Forest pipeline. It is not a diagnosis.</p><button className="button" onClick={()=>setStage('form')}>Begin entering measurements</button></div></main>;
if(stage==='processing')return <main className="page"><motion.div className="card" initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}}><h1>Preparing your result</h1><p>Validating measurements</p><p>Applying the fitted preprocessing pipeline</p><p>Running the liver model</p></motion.div></main>;
if(stage==='results')return <main className="page"><motion.div initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}}><p className="eyebrow">RESULT</p><h1>{result.label}</h1><div className="card"><h2>{Math.round((result.probability||0)*100)}% estimated probability</h2><p>Selected model: {result.selectedModel}</p><p>{result.disclaimer}</p><button className="button" onClick={pdf}>Download PDF report</button></div></motion.div></main>;
if(stage==='review')return <main className="page"><h1>Review liver measurements</h1><div className="card">{Object.entries(v).map(([k,x])=><p key={k}><strong>{labels[k]}:</strong> {x===null||x===''?'Not provided — model imputation will be used':String(x)}</p>)}<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I understand that this is an educational machine-learning prediction and not a medical diagnosis.</label><br/><button className="button" onClick={()=>setStage('form')}>Edit</button><button className="button" disabled={!ack} onClick={submit}>Run prediction</button>{error&&<p role="alert">{error}</p>}</div></main>;
const [title,keys]=groups[step];return <main className="page"><p className="eyebrow">STEP {step+1} OF 4</p><h1>{title}</h1><div className="card">{keys.map(k=><label key={k} style={{display:'block',margin:'18px 0'}}>{labels[k]}{k==='Gender'?<select aria-label={labels[k]} value={v.Gender} onChange={e=>set('Gender',e.target.value)}><option value="">Select gender</option><option>Male</option><option>Female</option></select>:<><input aria-label={labels[k]} type="number" inputMode={k==='Age'||['Alkphos','Sgpt','Sgot'].includes(k)?'numeric':'decimal'} step={k==='Age'||['Alkphos','Sgpt','Sgot'].includes(k)?1:0.01} disabled={k==='A/G Ratio'&&v['A/G Ratio']===null} value={k==='A/G Ratio'&&v['A/G Ratio']===null?'':(v as any)[k]} onChange={e=>set(k,e.target.value===''?'':Number(e.target.value))}/>{k==='A/G Ratio'&&<span><input type="checkbox" checked={v['A/G Ratio']===null} onChange={e=>set('A/G Ratio',e.target.checked?null:'')}/> Value unavailable</span>}</>}</label>)}<button className="button" onClick={()=>{const e=valid();if(e){setError(e);return}setError('');step?setStep(step-1):null}}>Back</button>{step<groups.length-1?<button className="button" onClick={()=>{const e=valid();if(e){setError(e);return}setStep(step+1)}}>Continue</button>:<button className="button" onClick={()=>{const e=valid();if(e){setError(e);return}setStage('review')}}>Review</button>}{error&&<p role="alert">{error}</p>}</div></main>}
