'use client';
import {useState} from 'react'; import {motion,useReducedMotion} from 'motion/react';
import {predictDisease,generateDiseaseReport} from '../../../lib/api';
type V={pregnancies:number|'';age:number|'';glucose:number|null|'';blood_pressure:number|null|'';skin_thickness:number|null|'';insulin:number|null|'';bmi:number|null|'';diabetes_pedigree:number|''};
const initial:V={pregnancies:'',age:'',glucose:'',blood_pressure:'',skin_thickness:'',insulin:'',bmi:'',diabetes_pedigree:''};
const groups=[['Patient profile',['pregnancies','age']],['Glucose and blood pressure',['glucose','blood_pressure']],['Body and insulin measurements',['skin_thickness','insulin','bmi']],['Family-risk measurement',['diabetes_pedigree']]] as const;
const labels:Record<string,string>={pregnancies:'Number of pregnancies',age:'Age',glucose:'Glucose concentration',blood_pressure:'Diastolic blood pressure',skin_thickness:'Triceps skinfold thickness',insulin:'Two-hour serum insulin',bmi:'Body mass index',diabetes_pedigree:'Diabetes pedigree function'};
export default function DiabetesAssessment(){const [stage,setStage]=useState<'intro'|'form'|'review'|'processing'|'results'>('intro'); const [step,setStep]=useState(0); const [v,setV]=useState<V>(initial); const [ack,setAck]=useState(false); const [result,setResult]=useState<any>(null); const [error,setError]=useState(''); const reduced=useReducedMotion();
 const set=(k:string,x:any)=>setV({...v,[k]:x}); const nullable=(k:string)=>v[k as keyof V]===null;
 const valid=()=>{for(const k of groups[step][1]){const x=v[k as keyof V]; if(x===''||x===undefined)return `${labels[k]} is required.`; if(typeof x==='number'&&x<0)return `${labels[k]} cannot be negative.`} return ''};
 async function submit(){setError('');setStage('processing'); try{const payload=Object.fromEntries(Object.entries(v).map(([k,x])=>[k,x===''?null:x])); const r=await predictDisease('diabetes',payload); setResult(r);setStage('results')}catch(e){setError('We could not run this assessment. Check the API and your measurements.');setStage('review')}}
 async function pdf(){try{const payload=Object.fromEntries(Object.entries(v).map(([k,x])=>[k,x===''?null:x]));const r=await generateDiseaseReport('diabetes',payload);if(!r.ok)throw Error();const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='diabetes-assessment-report.pdf';a.click()}catch{setError('The prediction is available, but the PDF could not be downloaded.')}}
 if(stage==='intro')return <main className="page"><p className="eyebrow">DIABETES ASSESSMENT</p><h1>Explore a diabetes risk pattern</h1><div className="card"><p>This educational assessment uses the Pima Indians Diabetes Database and a persisted SVM pipeline. It is not a diagnosis.</p><button className="button" onClick={()=>setStage('form')}>Begin entering measurements</button></div></main>;
 if(stage==='processing')return <main className="page"><motion.div initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} className="card"><h1>Preparing your result</h1><p>Validating measurements</p><p>Applying the fitted preprocessing pipeline</p><p>Running the diabetes model</p><p>Preparing the result</p></motion.div></main>;
 if(stage==='results')return <main className="page"><motion.div initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}}><p className="eyebrow">RESULT</p><h1>{result.label}</h1><div className="card"><h2>{result.probability===null?'Probability unavailable':`${Math.round(result.probability*100)}% estimated probability`}</h2><p>The model assigned this probability to the diabetes-present class based on the supplied measurements. Threshold: {result.threshold}.</p><p><strong>Selected model:</strong> {result.selectedModel}</p><p>{result.disclaimer}</p><button className="button" onClick={pdf}>Download PDF report</button> {error&&<p role="alert">{error}</p>}</div></motion.div></main>;
 if(stage==='review')return <main className="page"><h1>Review your measurements</h1><div className="card">{Object.entries(v).map(([k,x])=><p key={k}><strong>{labels[k]}:</strong> {x===null||x===''?'Not provided — model imputation will be used':String(x)}</p>)}<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I understand that this is an educational machine-learning prediction and not a medical diagnosis.</label><div><button className="button" onClick={()=>setStage('form')}>Edit</button><button className="button" disabled={!ack} onClick={submit}>Run prediction</button></div>{error&&<p role="alert">{error}</p>}</div></main>;
 const [title,keys]=groups[step]; return <main className="page"><p className="eyebrow">STEP {step+1} OF {groups.length}</p><h1>{title}</h1><div className="card">{keys.map(k=>{const isNull=nullable(k); return <label key={k} style={{display:'block',margin:'18px 0'}}>{labels[k]}<input aria-label={labels[k]} type="number" inputMode={k==='pregnancies'||k==='age'?'numeric':'decimal'} step={k==='bmi'?0.1:k==='diabetes_pedigree'?0.001:1} disabled={isNull} value={isNull?'':(v[k] as any)} onChange={e=>set(k,e.target.value===''?'':Number(e.target.value))}/>{['glucose','blood_pressure','skin_thickness','insulin','bmi'].includes(k)&&<span><input type="checkbox" checked={isNull} onChange={e=>set(k,e.target.checked?null:'')}/> Value unavailable</span>}</label>})}<p>Zero pregnancies is valid. For other unavailable measurements, use the checkbox so the fitted pipeline can impute them.</p><div>{step>0&&<button className="button" onClick={()=>setStep(step-1)}>Back</button>}{step<groups.length-1?<button className="button" onClick={()=>{const e=valid();if(e){setError(e);return}setError('');setStep(step+1)}}>Continue</button>:<button className="button" onClick={()=>{const e=valid();if(e){setError(e);return}setStage('review')}}>Review</button>}<button className="button" onClick={()=>{setV(initial);setStep(0);setStage('intro')}}>Reset</button></div>{error&&<p role="alert">{error}</p>}</div></main>}
