"""Generate checked-in frontend disease contracts from backend Pydantic models."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.api.contracts import FIELD_SPECS, MEASUREMENT_MODELS, contract_document  # noqa: E402
from src.model_release import load_release_manifest  # noqa: E402

OUT = ROOT / "frontend" / "features" / "assessments" / "generated"


def build_outputs() -> dict[Path, str]:
    manifest = load_release_manifest()
    for disease, model in MEASUREMENT_MODELS.items():
        expected = manifest["releases"][disease]["ordered_active_features"]
        model_fields = list(model.model_fields)
        if model_fields[:len(expected)] != expected:
            raise SystemExit(f"{disease} contract fields differ from release manifest: {model_fields} != {expected}")
    schemas = {}
    for disease, model in MEASUREMENT_MODELS.items():
        schema = model.model_json_schema()
        visible = [field["name"] for field in FIELD_SPECS[disease]]
        schema["properties"] = {name: schema["properties"][name] for name in visible}
        if "required" in schema:
            schema["required"] = [name for name in schema["required"] if name in visible]
        schemas[disease] = {"title": model.__name__, **schema}
    contract = contract_document()
    ts = "// Generated by scripts/generate_frontend_contracts.py. DO NOT EDIT.\n"
    ts += "export const diseaseContracts = " + json.dumps(contract["diseases"], ensure_ascii=False, indent=2) + " as const;\n"
    return {
        OUT / "contracts.ts": ts,
        OUT / "contracts.schema.json": json.dumps(schemas, ensure_ascii=False, indent=2) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    outputs = build_outputs()
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, value in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != value]
        if stale:
            print("Generated frontend contract is stale: " + ", ".join(stale), file=sys.stderr)
            return 1
        print("frontend disease contracts are current")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for path, value in outputs.items():
        path.write_text(value, encoding="utf-8", newline="\n")
        print(f"generated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
